name: Run Auto Sign 

on:
  workflow_dispatch:
  schedule:
    # Beijing Time 8:17 AM every day to avoid Github Action heavy load period
    - cron: "17 0 * * *"
    - cron: "0/10 * * * *"
    - cron: "10 * * * *"

env:
  COOKIES: ${{ secrets.COOKIES }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        id: build
        run: |
          npm install
      - name: Run 
        id: run
        run: |
          node main.js 
